### ISSUE TITLE
iOS: 2.0.0 has no control buttons!

### ISSUE THREAD

**Issue by shawnlan** [homerours/cordova-music-controls-plugin#75] opened 2017-07-07 22:44 UTC
1.4.1 works fine, but 2.0.0 control buttons are missing from the control center.

**Comment by RBrenet** [comment] 2017-07-11 07:19
Yes I have the same issue

**Comment by soramister** [comment] 2017-07-16 07:56
I can confirm. My play/pause button disappear on my iPhone device.

**Comment by RomainDev25** [comment] 2017-07-17 12:24
Ok, if I replace MusicControls.m By an older project it's OK : 

`//
//  MusicControls.m
//  
//
//  Created by Juan Gonzalez on 12/16/16.
//
//

#import "MusicControls.h"
#import "MusicControlsInfo.h"

@implementation MusicControls

- (void) create: (CDVInvokedUrlCommand *) command {
    NSDictionary * musicControlsInfoDict = [command.arguments objectAtIndex:0];
    MusicControlsInfo * musicControlsInfo = [[MusicControlsInfo alloc] initWithDictionary:musicControlsInfoDict];
    
    if (!NSClassFromString(@"MPNowPlayingInfoCenter")) {
        return;
    }
    
    [self.commandDelegate runInBackground:^{
        MPNowPlayingInfoCenter * nowPlayingInfoCenter =  [MPNowPlayingInfoCenter defaultCenter];
        NSDictionary * nowPlayingInfo = nowPlayingInfoCenter.nowPlayingInfo;
        NSMutableDictionary * updatedNowPlayingInfo = [NSMutableDictionary dictionaryWithDictionary:nowPlayingInfo];
        
        MPMediaItemArtwork * mediaItemArtwork = [self createCoverArtwork:[musicControlsInfo cover]];
        NSNumber * duration = [NSNumber numberWithInt:[musicControlsInfo duration]];
        NSNumber * elapsed = [NSNumber numberWithInt:[musicControlsInfo elapsed]];
        NSNumber * playbackRate = [NSNumber numberWithBool:[musicControlsInfo isPlaying]];
        
        if (mediaItemArtwork != nil) {
            [updatedNowPlayingInfo setObject:mediaItemArtwork forKey:MPMediaItemPropertyArtwork];
        }
        
        [updatedNowPlayingInfo setObject:[musicControlsInfo artist] forKey:MPMediaItemPropertyArtist];
        [updatedNowPlayingInfo setObject:[musicControlsInfo track] forKey:MPMediaItemPropertyTitle];
        [updatedNowPlayingInfo setObject:[musicControlsInfo album] forKey:MPMediaItemPropertyAlbumTitle];
        [updatedNowPlayingInfo setObject:duration forKey:MPMediaItemPropertyPlaybackDuration];
        [updatedNowPlayingInfo setObject:elapsed forKey:MPNowPlayingInfoPropertyElapsedPlaybackTime];
        [updatedNowPlayingInfo setObject:playbackRate forKey:MPNowPlayingInfoPropertyPlaybackRate];
        
        nowPlayingInfoCenter.nowPlayingInfo = updatedNowPlayingInfo;
    }];
}

- (void) updateIsPlaying: (CDVInvokedUrlCommand *) command {
    NSDictionary * musicControlsInfoDict = [command.arguments objectAtIndex:0];
    MusicControlsInfo * musicControlsInfo = [[MusicControlsInfo alloc] initWithDictionary:musicControlsInfoDict];
    NSNumber * playbackRate = [NSNumber numberWithBool:[musicControlsInfo isPlaying]];
    
    if (!NSClassFromString(@"MPNowPlayingInfoCenter")) {
        return;
    }

    MPNowPlayingInfoCenter * nowPlayingCenter = [MPNowPlayingInfoCenter defaultCenter];
    NSMutableDictionary * updatedNowPlayingInfo = [NSMutableDictionary dictionaryWithDictionary:nowPlayingCenter.nowPlayingInfo];
    
    [updatedNowPlayingInfo setObject:playbackRate forKey:MPNowPlayingInfoPropertyPlaybackRate];
    nowPlayingCenter.nowPlayingInfo = updatedNowPlayingInfo;
}

- (void) destroy: (CDVInvokedUrlCommand *) command {
    [self deregisterMusicControlsEventListener];
}

- (void) watch: (CDVInvokedUrlCommand *) command {
    [self setLatestEventCallbackId:command.callbackId];
    [self registerMusicControlsEventListener];
}

- (MPMediaItemArtwork *) createCoverArtwork: (NSString *) coverUri {
    UIImage * coverImage = nil;
    
    if (coverUri == nil) {
        return nil;
    }
    
    if ([coverUri hasPrefix:@"http://"] || [coverUri hasPrefix:@"https://"]) {
        NSURL * coverImageUrl = [NSURL URLWithString:coverUri];
        NSData * coverImageData = [NSData dataWithContentsOfURL: coverImageUrl];
        
        coverImage = [UIImage imageWithData: coverImageData];
    }
    else if ([coverUri hasPrefix:@"file://"]) {
        NSString * fullCoverImagePath = [coverUri stringByReplacingOccurrencesOfString:@"file://" withString:@""];
        
        if ([[NSFileManager defaultManager] fileExistsAtPath: fullCoverImagePath]) {
            coverImage = [[UIImage alloc] initWithContentsOfFile: fullCoverImagePath];
        }
    }
    else if (![coverUri isEqual:@""]) {
        NSString * baseCoverImagePath = [NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES) objectAtIndex:0];
        NSString * fullCoverImagePath = [NSString stringWithFormat:@"%@%@", baseCoverImagePath, coverUri];
    
        if ([[NSFileManager defaultManager] fileExistsAtPath:fullCoverImagePath]) {
            coverImage = [UIImage imageNamed:fullCoverImagePath];
        }
    }
    else {
        coverImage = [UIImage imageNamed:@"none"];
    }
    
    return [self isCoverImageValid:coverImage] ? [[MPMediaItemArtwork alloc] initWithImage:coverImage] : nil;
}

- (bool) isCoverImageValid: (UIImage *) coverImage {
    return coverImage != nil && ([coverImage CIImage] != nil || [coverImage CGImage] != nil);
}

- (void) handleMusicControlsNotification: (NSNotification *) notification {
    UIEvent * receivedEvent = notification.object;
    
    if ([self latestEventCallbackId] == nil) {
        return;
    }
    
    if (receivedEvent.type == UIEventTypeRemoteControl) {
        NSString * action;
        
        switch (receivedEvent.subtype) {
            case UIEventSubtypeRemoteControlTogglePlayPause:
                action = @"music-controls-toggle-play-pause";
                break;
                
            case UIEventSubtypeRemoteControlPlay:
                action = @"music-controls-play";
                break;
                
            case UIEventSubtypeRemoteControlPause:
                action = @"music-controls-pause";
                break;
                
            case UIEventSubtypeRemoteControlPreviousTrack:
                action = @"music-controls-previous";
                break;
                
            case UIEventSubtypeRemoteControlNextTrack:
                action = @"music-controls-next";
                break;
                
            case UIEventSubtypeRemoteControlStop:
                action = @"music-controls-destroy";
                break;
                
            default:
                break;
        }
        
        CDVPluginResult * pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK messageAsString:action];
        [self.commandDelegate sendPluginResult:pluginResult callbackId:[self latestEventCallbackId]];
    }
}

- (void) registerMusicControlsEventListener {
    [[UIApplication sharedApplication] beginReceivingRemoteControlEvents];
    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(handleMusicControlsNotification:) name:@"musicControlsEventNotification" object:nil];
}

- (void) deregisterMusicControlsEventListener {
    [[UIApplication sharedApplication] endReceivingRemoteControlEvents];
    [[NSNotificationCenter defaultCenter] removeObserver:self name:@"receivedEvent" object:nil];
    [self setLatestEventCallbackId:nil];
}

- (void) dealloc {
    [self deregisterMusicControlsEventListener];
}

@end
`

I will search in detail the problem

**Comment by RomainDev25** [comment] 2017-07-17 12:41
Ok, it's a problem with this methods : 

handleMusicControlsNotification
registerMusicControlsEventListener
changedThumbSliderOnLockScreen
deregisterMusicControlsEventListener

**Comment by BuddyLReno** [comment] 2017-07-17 12:42
I can verify in my app the play/pause doesn't disappear but I don't have forward and back buttons. I've not been able to figure that out yet.

**Comment by BuddyLReno** [comment] 2017-07-17 12:43
We do want to make sure that we keep the json messaging system.

**Comment by RomainDev25** [comment] 2017-07-17 12:50
I think the problem is the json messaging system, because, when I disable it, it's ok.

**Comment by BuddyLReno** [comment] 2017-07-17 13:10
Ok, let's see what needs to change to keep the json system. That system is needed to pass data to be able to change the elapsed time from the iOS control center. What version of iOS do you experience the error on? I wasn't seeing an issue on my 10.2 and 10.3 devices. (full disclosure, I don't know objective-c or swift, mainly a javascript/ruby dev)

**Comment by RomainDev25** [comment] 2017-07-17 13:28
I have iOS 10.3.2.

I have replace MusicControls.m

https://github.com/homerours/cordova-music-controls-plugin/files/1152562/MusicControls.m.txt

**Comment by soramister** [comment] 2017-07-17 13:54
I have it on 10.3.2 too.

**Comment by RomainDev25** [comment] 2017-07-17 14:11
@soramister I have use this tree : 
https://github.com/homerours/cordova-music-controls-plugin/tree/f97fb2cb12232c3d66f4e4bb0c14853ff7188dbf

You download this plugin am^nd you add locally with : 
cordova plugin add  {PATHPLUGIN} 

I have copy this plugin in plugins/cordova-music-control
So I type : 
cordova plugin add ./plugins/cordova-music-control

And it's OK

**Comment by soramister** [comment] 2017-07-17 14:28
Thanks but I rolled back to 1.4.1 for now which is working so it is ok.

But it would be nice that the 2.0.0 has a bug fix for the future.

**Comment by maurizio96** [comment] 2017-08-08 16:18
Hi @soramister ,
I had the same problem with 2.0.0. I tried 1.4.1 but unfortunately it gives some errors about JSON parse on messaging. How did you solve it? 

`cordova plugin list`

shows correctly the 1.4.1.

I have also tried to apply manually "_MusicControls.m_" you attached but nothing has changed

Thank you

**Comment by marcari** [comment] 2017-08-18 15:50
See PR #78 for a fix. Works fine on iOS 10.0 & 10.3.

**Comment by fdambrosio** [comment] 2017-09-28 14:18
will be fixed on 2.1.0?

**Comment by bensinclair** [comment] 2017-11-21 00:44
+1 for a fix

**Comment by ghenry22** [comment] 2017-11-21 06:29
Please try the current release, just install directly from the github repo as NPM is not updated yet.

Recent fix I committed has all buttons working again as they should on iOS.

**Comment by fdambrosio** [comment] 2017-11-21 11:51
@bensinclair it works if you do: 
```
npm remove cordova-plugin-music-controls
npm install https://github.com/homerours/cordova-music-controls-plugin --save
ionic cordova plugin rm cordova-plugin-music-controls
ionic cordova plugin add https://github.com/homerours/cordova-music-controls-plugin
```

**Closed** 2017-11-21 13:19 UTC
