### ISSUE TITLE
iOS 11 Events do not work correctly

### ISSUE THREAD

**Issue by soniyj** [homerours/cordova-music-controls-plugin#90] opened 2017-10-25 15:18 UTC
I am facing some issues in iOS 11 with the new control center, in fact when you press the buttons play/pause or skip, events are not fired correctly and always. When you press one of the buttons the event is not recognised and if you press another button it runs the one pressed before.
Also sometimes the timeline is not updated, you have to open the player from the control center.

I am trying to debug the Obj-C code but no error and no Apple useful doc (as usual).

**Comment by fdambrosio** [comment] 2017-10-27 08:50
I had the same problem. I have to use 1.4.1 version. 2.x/2.1.1 too is not working, play/pause event are not fired. 
Using 1.4.1 you have to try this code: 

```
this.myControls.subscribe().subscribe((action) => {
                    switch(action) {
....
```

**Comment by soniyj** [comment] 2017-10-27 09:49
Thanks @fdambrosio I am already using that code, I was debugging both the JS and the Objective-C code and when you press any buttons the events from the Obj-C code do not seem to be fired, this it happens with iOS 11 if you run the same code on iOS 10.x it works. I will test the 1.4.1 and see how it goes.

**Comment by carlosstrand** [comment] 2017-10-31 19:36
@soniyj I had this problem today. I solved by adding:

```
if (action == nil) {
    return;
}
```

at the end of the switch / case of the plugin (Objective-C). I saw that sometimes the action came `nil`, I believe something related to a debounce.

All handler below:

```
- (void) handleMusicControlsNotification: (NSNotification *) notification {
    UIEvent * receivedEvent = notification.object;
    
    if ([self latestEventCallbackId] == nil) {
        return;
    }
    
    if (receivedEvent.type == UIEventTypeRemoteControl) {
        NSString * action;

        switch (receivedEvent.subtype) {
            case UIEventSubtypeRemoteControlTogglePlayPause:
                action = @"music-controls-toggle-play-pause";
                break;

            case UIEventSubtypeRemoteControlPlay:
                action = @"music-controls-play";
                break;

            case UIEventSubtypeRemoteControlPause:
                action = @"music-controls-pause";
                break;

            case UIEventSubtypeRemoteControlPreviousTrack:
                action = @"music-controls-previous";
                break;

            case UIEventSubtypeRemoteControlNextTrack:
                action = @"music-controls-next";
                break;

            case UIEventSubtypeRemoteControlStop:
                action = @"music-controls-destroy";
                break;

            default:
                action = nil;
                break;
        }

        if (action == nil) {
            return;
        }
        
        CDVPluginResult * pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK messageAsString:action];
        [self.commandDelegate sendPluginResult:pluginResult callbackId:[self latestEventCallbackId]];
    }
}
```

**Comment by soniyj** [comment] 2017-11-01 10:41
hi @carlosstrand cool I will have a look. Which version of the plugin are you using? I tried the 1.4.x how suggested but that doesn't even show the right info. Another strange thing with the new info center is that sometimes the progress bar is not updated especially when the player is inside the center info.

**Comment by carlosstrand** [comment] 2017-11-01 16:54
I am using the 1.4.1

**Comment by soniyj** [comment] 2017-11-01 17:51
@carlosstrand ok but the 1.4.1 doesn't show anything!

**Comment by ghenry22** [comment] 2017-11-06 09:29
@carlosstrand - Nice call there.  Fixed the music controls plugin for me on ios11.

I am using plugin version 1.4.1, cordova-ios 4.5.3.

I added some logging in while trying to troubleshoot this and it seems that you get a flood of events whenever you hit one of the remote control buttons and they get caught by the default switch case and anything after the first one to hit that default case returns NULL to javascript.  Except play and pause weirdly which continue to work.

It seems like really weird behaviour!

**Comment by soniyj** [comment] 2017-11-06 10:53
@ghenry22 I will try the old 1.4.1 with cordova 4.5.3 without @carlosstrand suggestion, if it doens't work I will add that line of code.

I also added some logging as you did and in fact it seems that events are not propagated correctly, sometimes it is ok and sometimes they seem to go in a queue and processed in one go.

**Comment by BuddyLReno** [comment] 2017-11-06 13:24
I'm trying this fix out now. My top priority over the next couple days is fixing up this plugin.

**Comment by BuddyLReno** [comment] 2017-11-06 13:26
ANY help with this though is super appreciated. My main set of skills is front-end development, so iOS/Android stuff is trial and error for me usually.

**Comment by BuddyLReno** [comment] 2017-11-06 16:20
Ok so the interesting part for me is thus:

Using Ionic UIWebview: The events and notification function exactly as should and expected.

Using Ionic WKWebview: Play button is grayed out and when I press the button for skip forward or backward, the event is called an extra time each time I press it: 

- First press: called twice
- Second press: called three times
- Third press: called four times.

and so on.

**Comment by BuddyLReno** [comment] 2017-11-06 16:43
Discovered that registerMusicControlsEventListener is being called multiple times which is likely the cause of a host of issues.

**Comment by BuddyLReno** [comment] 2017-11-06 21:14
@carlosstrand I'm adding in the code you suggested about the action being nil in this next commit.

**Comment by BuddyLReno** [comment] 2017-11-06 21:34
@fdambrosio @soniyj can you guys try PR #95? I've gotten positive results with those fixes.

**Comment by soniyj** [comment] 2017-11-07 11:08
Hi @BuddyLReno I will test it, is this merged into the actual repository?

Just as info, the plugin works fine on iOS 10.x with the old UIWebView as you said, in fact strange things have started to happen since the new iOS SDK 11 (no surprise from Apple) and Ionic.

I am not an Obj-C expert but in case I am willing to help, I also tried to convert this to Swift but I got the same issue.

**Comment by BuddyLReno** [comment] 2017-11-07 13:41
@soniyj Thanks man. I'm currently taking a look at PR #96 which looks extremely promising. I'm definitely not an Obj-C expert by any stretch of the imagination. I think I inadvertently inherited the repo, lol :)

**Comment by soniyj** [comment] 2017-11-07 13:56
@BuddyLReno not a problem, hoping to find a way. Cool this sounds really good. Hahaha no worries I think people are here to help ;)

**Comment by fdambrosio** [comment] 2017-11-08 11:26
Hi @BuddyLReno I've tested 2.1.3 merge with Ionic Native Music Control 4.3.2 and UIWebview. 
Play/Pause event and hasPrev/hasNext false WORKS correctly on iOS. 
iOS 9 & iOS 10 works on Simulator. iOS 11 works on Device. 

example repo: https://github.com/fdambrosio/ionic-media-controls/tree/merge96

**Comment by BuddyLReno** [comment] 2017-11-08 13:11
@fdambrosio great! Thanks for checking it out! I am going to close this issue as I'm receiving reports elsewhere that this topic is fixed.

**Closed by BuddyLReno** 2017-11-08 13:11 UTC
Labels: help wanted

**Comment by soniyj** [comment] 2017-11-09 11:18
Hello @fdambrosio and @BuddyLReno which branch I should test with iOS 11? Is that working just with UIWebView? thanks

**Comment by fdambrosio** [comment] 2017-11-09 11:27
@soniyj the latest 2.1.3 music control plugin (master branch) works fine with UIWebView and iOS11 (only using the device) 
My sample repo works, you can check my environment: https://github.com/fdambrosio/ionic-media-controls

**Comment by BuddyLReno** [comment] 2017-11-09 13:34
@soniyj we're still fighting some weird issues with WKWebview which may result in how Ionic has WKWebview configured. @ghenry22 is messing with that.

**Comment by soniyj** [comment] 2017-11-10 11:34
@fdambrosio I will test the latest version from the repos, as the tag release is still at 2.1.2, I will test on both UI and WK, and see how it works. Thanks for sharing it!

@BuddyLReno and @ghenry22 any chance to get in touch with the Ionic guys about it?

**Comment by BuddyLReno** [comment] 2017-11-10 13:28
I may put in some sort of support ticket. The issue hinders us from moving to WKWebview. Using the media plugin, we subscribe to the onStatusUpdate observer and run an action that starts the next track when the current track is finished. That functionality breaks in WK but works in UI. I'm going to pop over to the media plugin and investigate there too.

**Comment by soniyj** [comment] 2017-11-10 17:33
@BuddyLReno cool, can you also mention that the media plugin should have a callback when a media has loaded or not, right now the callbacks are not really useful especially when you need events to be fired right after. We are looking into it next week because we need something like that.
